app_index:
    path: /
    defaults: { _controller: AppBundle:Default:index }
    
YML_Auth:
    resource: "@AppBundle/Resources/config/routing/authentication.yml"
    prefix: /
    
YML_Admin:
    resource: "@AppBundle/Resources/config/routing/admin.yml"
    prefix: /admin
    
YML_Teacher:
    resource: "@AppBundle/Resources/config/routing/teacher.yml"
    prefix: /teacher
    
YML_Student:
    resource: "@AppBundle/Resources/config/routing/student.yml"
    prefix: /student
   
app_test_admin:
    path: /test/admin
    defaults: { _controller: AppBundle:Test:testAdmin }
    
